### ISSUE TITLE
Bug: ocamlformat_reason ~dev doesn't compile (opam 2.0.5 / ocaml 4.07.1)

### ISSUE THREAD

**Issue by RogerTarani** [ocaml-ppx/ocamlformat#1035]
Any idea for installing ocamlformat_reason ~dev?

Not ok with `ocamlformat_reason ~dev`:
```
$ opam pin add ocamlformat_reason https://github.com/ocaml-ppx/ocamlformat.git
Package ocamlformat_reason does not exist, create as a NEW package? [Y/n] y
[ocamlformat_reason.~dev] synchronised from git+https://github.com/ocaml-ppx/ocamlformat.git
ocamlformat_reason is now pinned to git+https://github.com/ocaml-ppx/ocamlformat.git (version ~dev)

The following actions will be performed:
  ∗ install ocamlformat_reason ~dev*
Do you want to continue? [Y/n] y
[ocamlformat_reason.~dev] synchronised from git+https://github.com/ocaml-ppx/ocamlformat.git

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ERROR] The compilation of ocamlformat_reason failed at "/home/rt/.opam/opam-init/hooks/sandbox.sh build
        dune build -p ocamlformat_reason -j 1".

#=== ERROR while compiling ocamlformat_reason.~dev ============================#
# context     2.0.5 | linux/x86_64 | ocaml-base-compiler.4.07.1 | pinned(git+https://github.com/ocaml-ppx/ocamlformat.git#ce9e5393)
# path        ~/.opam/4.07.1/.opam-switch/build/ocamlformat_reason.~dev
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p ocamlformat_reason -j 1
# exit-code   1
# env-file    ~/.opam/log/ocamlformat_reason-10335-d6d332.env
# output-file ~/.opam/log/ocamlformat_reason-10335-d6d332.out
### output ###
#        ocaml (internal) (exit 2)
# (cd test/passing && /home/rt/.opam/4.07.1/bin/ocaml -I +compiler-libs /home/rt/.opam/4.07.1/.opam-switch/build/ocamlformat_reason.~dev/_build/.dune/default/test/passing/dune.ml)
# File "test/passing/dune", line 54, characters 23-35:
# Error: Unbound module Option


<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build ocamlformat_reason ~dev
└─ 
╶─ No changes have been performed
[NOTE] Pinning command successful, but your installed packages may be out of sync.
```

Ok for that three packages:
```
┌─ The following changes have been performed
│ ∗ install menhir        20190924
│ ∗ install merlin-extend 0.5
│ ∗ install reason        3.5.0
└─ 
```

**Comment by RogerTarani** [comment]
This command works:
`$ opam pin add ocamlformat_reason https://github.com/ocaml-ppx/ocamlformat.git#v0.11.0`

What is the correct URL?
What about registering ocaml_reason in [packages.opam.org](url)?

BTW, can you explain how to simply convert a reason file or a files tree in OCaml files(s)?
Thanks.

**Comment by Julow** [comment]
Indeed it does not build with 4.07.1. I'm looking into it.

I agree it would be great to release it. What do you think @gpetiot ?

It works like this: `refmt -p binary_reason input_file.re | ocamlformat --impl --name x.ml - > output_file.ml`

**Comment by RogerTarani** [comment]
Thanks. It works now:
```
$ opam pin add ocamlformat_reason https://github.com/ocaml-ppx/ocamlformat.git#0.11.0
...
∗ installed ocamlformat_reason.0.11.0
Done.
```

I just want to convert a file from Reasonml syntax to Ocaml syntax. With the following command I get a binary file:
```
refmt -p binary_reason input.re | ocamlformat --impl --name x.ml - > output.ml
```
With the following (with **re**, which is default, instead of **binary_reason**), I get a reason syntax file as output with a few spaces modified:
```
refmt -p re input.re | ocamlformat --impl --name x.ml - > output.ml
```
Let's see... The solution is:
```
refmt -p ml input.re | ocamlformat --impl --name x.ml - > output.ml
```
Using `--enable-outside-detected-project` for ocamlformat event helps to get rid of the following warning:
```
File "x.ml":
Warning: Ocamlformat disabled because [--enable-outside-detected-project] is not set and no project root was found 
```
What would be the straightest way to convert an .ml into .re?

**Comment by Julow** [comment]
The command is
```
refmt -p binary_reason input_file.re | ocamlformat_reason --impl --name x.ml - > output_file.ml
```
`ocamlformat_reason` is a different command. Sorry, I made a typo in my previous message.

**Comment by RogerTarani** [comment]
For me, your command outputs the same reason file:
`$ refmt -p binary_reason input_file.re | ocamlformat_reason --impl --name x.ml - > output_file.ml`

I could get an Ocaml file with the command mentioned herebefore:
`$ refmt -p ml input.re | ocamlformat --impl --name x.ml - > output.ml
`

Can you pls. check?
Thanks

**Comment by hhugo** [comment]
@RogerTarani, I suspect the second command will drop all comments

**Comment by RogerTarani** [comment]
which comments?

**Comment by hhugo** [comment]
Comments in your reason file

**Comment by Julow** [comment]
OCamlformat won't output reason code. The first command works for me.
The second command works by asking `refmt` to output OCaml code but it will remove the comments.
