### ISSUE TITLE
OCaml 5.3 support

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml-ppx/ocamlformat#2576]
ocamlformat current fails to build with OCaml 5.3:
```
#=== ERROR while compiling ocamlformat-lib.0.26.2 =============================#
# context              2.3.0~alpha~dev | linux/x86_64 | ocaml-variants.5.3.0+trunk | file:///home/opam/opam-repository
# path                 ~/.opam/5.3/.opam-switch/build/ocamlformat-lib.0.26.2
# command              ~/.opam/5.3/bin/dune build -p ocamlformat-lib -j 1 @install
# exit-code            1
# env-file             ~/.opam/log/ocamlformat-lib-20-cfb175.env
# output-file          ~/.opam/log/ocamlformat-lib-20-cfb175.out
### output ###
# (cd _build/default && /home/opam/.opam/5.3/bin/ocamlc.opt -w -40 -noassert -w -9 -open Parser_shims -g -bin-annot -bin-annot-occurrences -I vendor/ocaml-common/.ocaml_common.objs/byte -I /home/opam/.opam/5.3/lib/ocaml/compiler-libs -I vendor/parser-shims/.parser_shims.objs/byte -intf-suffix .ml -no-alias-deps -open Ocaml_common -o vendor/ocaml-common/.ocaml_common.objs/byte/ocaml_common__Location.cmo -c -impl vendor/ocaml-common/location.ml)
# File "vendor/ocaml-common/location.ml", line 505, characters 8-27:
# 505 |         Misc.pp_two_columns ~sep:"|" ~max_lines ppf
#               ^^^^^^^^^^^^^^^^^^^
# Error: Unbound value "Misc.pp_two_columns"
```

**Comment by kit-ty-kate** [comment]
Hi, has there been any progress on this by any chance?

**Comment by Julow** [comment]
Work have been done in https://github.com/ocaml-ppx/ocamlformat/pull/2562 but we're still currently finalizing 5.2 support.

**Comment by kit-ty-kate** [comment]
Hi, do you have any update on this by any chance? The release is getting closer and this is going to become quite urgent quite quickly

**Comment by Julow** [comment]
Hi, the work is in progress. We build on 5.3 since https://github.com/ocaml-ppx/ocamlformat/pull/2603 but some work is still needed to format 5.3 code (`effect` syntax, keyword versioning, backporting the many lexer and parser changes)

**Comment by hhugo** [comment]
Can this be closed or are there still some changes needed ?

**Comment by Julow** [comment]
Since https://github.com/ocaml-ppx/ocamlformat/pull/2624 and https://github.com/ocaml-ppx/ocamlformat/pull/2625, this is finally complete !

**Comment by kit-ty-kate** [comment]
Thanks a lot! Could we get a release by any chance?

**Comment by Julow** [comment]
The last thing on my list before a release is to update the vendored Odoc parser. I hope to release soon.

**Comment by Julow** [comment]
Released :tada:
